#!/usr/bin/env python

import sys, os, re
from subprocess import check_output

# Collect the parameters
commit_msg_filepath = sys.argv[1]
if len(sys.argv) > 2:
    sys.exit(0)

# Figure out which branch we're on
try:
    branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).strip()
except Exception:
    exit()
print "prepare-commit-msg: On branch '%s'" % branch

# Populate the commit message with the issue #, if there is one
if branch.startswith('feature/'):
    print "prepare-commit-msg: Oh hey, it's a feature branch."
    result = re.match('feature/(.*)', branch)
    issue_number = result.group(1)

    with open(commit_msg_filepath, 'r+') as f:
        content = f.read()
        f.seek(0, 0)
        f.write("%s: \n%s" % (issue_number, content))

